//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NONBAOHIEMVIETTIN.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class news
    {
        public int id { get; set; }
        public Nullable<int> id_newstype { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string image { get; set; }
        [JsonIgnore]


        public virtual newstype newstype { get; set; }
    }
}
