//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NONBAOHIEMVIETTIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> idaccount { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string email { get; set; }
        public string fullname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> statuspay { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual accounts accounts { get; set; }
    }
}
