//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NONBAOHIEMVIETTIN.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.orderdetail = new HashSet<orderdetail>();
            this.rate = new HashSet<rate>();
            this.receiptdetail = new HashSet<receiptdetail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> promationprice { get; set; }
        public Nullable<int> quantity { get; set; }
        public string description { get; set; }
        public Nullable<int> viewcount { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string image { get; set; }
        public Nullable<bool> fastsell { get; set; }
        public Nullable<bool> newproduct { get; set; }
        public Nullable<int> idcategory { get; set; }
        public Nullable<int> idproduction { get; set; }
        public Nullable<int> idgroupproduct { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public string moreimage { get; set; }
        [JsonIgnore]

        public virtual category category { get; set; }
        [JsonIgnore]

        public virtual groupproduct groupproduct { get; set; }
        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderdetail> orderdetail { get; set; }
        [JsonIgnore]

        public virtual production production { get; set; }
        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rate> rate { get; set; }
        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receiptdetail> receiptdetail { get; set; }
    }
}
