//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NONBAOHIEMVIETTIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int id { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> promationprice { get; set; }
        public Nullable<int> quantity { get; set; }
        public string description { get; set; }
        public Nullable<int> viewcount { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string image { get; set; }
        public Nullable<bool> fastsell { get; set; }
        public Nullable<bool> newproduct { get; set; }
        public Nullable<int> idcategory { get; set; }
        public Nullable<int> idproduction { get; set; }
        public Nullable<int> idgroupproduct { get; set; }
    
        public virtual category category { get; set; }
        public virtual groupproduct groupproduct { get; set; }
        public virtual production production { get; set; }
    }
}
