
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NONBAOHIEMVIETTIN.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class promotion
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public promotion()
        {

            this.order = new HashSet<order>();

            this.wheel = new HashSet<wheel>();

        }


        public int id { get; set; }

        public string name { get; set; }

        public Nullable<System.DateTime> create_date { get; set; }

        public Nullable<System.DateTime> start_date { get; set; }

        public Nullable<System.DateTime> end_date { get; set; }

        public Nullable<int> create_by { get; set; }

        public Nullable<int> discount { get; set; }

        public Nullable<int> quantity_use { get; set; }

        public string alias { get; set; }

        public string code { get; set; }

        [JsonIgnore]
        public virtual accounts accounts { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<order> order { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<wheel> wheel { get; set; }

    }

}
