//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NONBAOHIEMVIETTIN.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class rate
    {
        public int id { get; set; }
        public Nullable<int> id_account { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> star { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        [JsonIgnore]

        public virtual accounts accounts { get; set; }
        [JsonIgnore]

        public virtual products products { get; set; }
    }
}
