
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NONBAOHIEMVIETTIN.Models
{

using System;
    using System.Collections.Generic;
    
public partial class receiptdetail
{

    public int idproduct { get; set; }

    public int idreceipt { get; set; }

    public decimal price { get; set; }

    public int quantity { get; set; }

    public decimal subtotal { get; set; }



    public virtual products products { get; set; }

    public virtual receipt receipt { get; set; }

}

}
