using System.Text.Json.Serialization;

namespace NonBaoHiemVietTin.Models;

public class Account { public int Id {get;set;} public int? IdRole {get;set;} public string? Username {get;set;} public string? Password {get;set;} public string? Image {get;set;} public string? Fullname {get;set;} public string? Email {get;set;} public string? Phone {get;set;} public string? Address {get;set;} public bool? Status {get;set;} public int? IsSocial {get;set;} public string? Alias {get;set;} public DateTime? CreateDate {get;set;} public int? Coin {get;set;} public DateTime? DateAttendance {get;set;} public int? Spin {get;set;} }
public class Product { public int Id {get;set;} public string? Name {get;set;} public string? Alias {get;set;} public bool? Status {get;set;} public decimal? Price {get;set;} public decimal? PromationPrice {get;set;} public int? Quantity {get;set;} public string? Description {get;set;} public int? ViewCount {get;set;} public DateTime? CreatedDate {get;set;} public string? Image {get;set;} public bool? FastSell {get;set;} public bool? NewProduct {get;set;} public int? IdCategory {get;set;} public int? IdProduction {get;set;} public int? IdGroupProduct {get;set;} public bool? IsDelete {get;set;} public string? MoreImage {get;set;} }
public class Category { public int Id {get;set;} public string? Name {get;set;} public string? Alias {get;set;} public bool? Status {get;set;} public bool? IsDelete {get;set;} }
public class GroupProduct { public int Id {get;set;} public string? Name {get;set;} public string? Alias {get;set;} public bool? Status {get;set;} public bool? IsDelete {get;set;} }
public class Production { public int Id {get;set;} public string? Name {get;set;} public string? Alias {get;set;} public bool? Status {get;set;} public bool? IsDelete {get;set;} }
public class Order { public int Id {get;set;} public int? IdAccount {get;set;} public DateTime? CreateDate {get;set;} public string? Email {get;set;} public string? Fullname {get;set;} public string? Address {get;set;} public string? Phone {get;set;} public bool? Status {get;set;} public bool? StatusPay {get;set;} public decimal? Total {get;set;} public string? Note {get;set;} public int? PaymentMethod {get;set;} public int? IdPromotion {get;set;} }
public class OrderDetail { public int IdProduct {get;set;} public int IdOrder {get;set;} public decimal? Price {get;set;} public int? Quantity {get;set;} public decimal? Subtotal {get;set;} }
public class Rate { public int Id {get;set;} public int? IdAccount {get;set;} public int? IdProduct {get;set;} public int? Star {get;set;} public string? Comment {get;set;} public DateTime? CreateDate {get;set;} }
public class Role { public int Id {get;set;} public string? Name {get;set;} public string? Alias {get;set;} }
public class Brand { public int Id {get;set;} public string? Name {get;set;} public string? Alias {get;set;} public string? Image {get;set;} public string? Link {get;set;} }
public class News { public int Id {get;set;} public int? IdNewsType {get;set;} public string? Title {get;set;} public string? Alias {get;set;} public string? Content {get;set;} public DateTime? CreateDate {get;set;} public string? Image {get;set;} }
public class NewsType { public int Id {get;set;} public string? Name {get;set;} public string? Alias {get;set;} }
public class Contact { public int Id {get;set;} public string? Title {get;set;} public string? Content {get;set;} public string? Address {get;set;} public string? Email {get;set;} public string? Phone {get;set;} public string? WorkTime {get;set;} public string? Map {get;set;} public bool? Display {get;set;} public string? WorkDay {get;set;} public string? Alias {get;set;} }
public class Feedback { public int Id {get;set;} public string? Name {get;set;} public string? Email {get;set;} public string? Phone {get;set;} public string? Subject {get;set;} public string? Message {get;set;} }
public class Introduce { public int Id {get;set;} public string? Title {get;set;} public string? Content {get;set;} public string? Image {get;set;} public bool? Status {get;set;} public string? Alias {get;set;} }
public class Promotion { public int Id {get;set;} public string? Name {get;set;} public DateTime? CreateDate {get;set;} public DateTime? StartDate {get;set;} public DateTime? EndDate {get;set;} public int? CreateBy {get;set;} public int? Discount {get;set;} public int? QuantityUse {get;set;} public string? Alias {get;set;} public string? Code {get;set;} }
public class Receipt { public int Id {get;set;} public int? IdAccount {get;set;} public DateTime? CreateDate {get;set;} public decimal? Total {get;set;} }
public class ReceiptDetail { public int IdProduct {get;set;} public int IdReceipt {get;set;} public decimal Price {get;set;} public int Quantity {get;set;} public decimal Subtotal {get;set;} }
public class Subscribe { public int Id {get;set;} public string? Email {get;set;} }
public class Wheel { public int Id {get;set;} public int? IdAccount {get;set;} public int? IdPromotion {get;set;} public DateTime? CreateDate {get;set;} public string? GiftName {get;set;} }
public class HistoryRecharge { public int Id {get;set;} public int? IdAccount {get;set;} public int? AmountMoney {get;set;} public DateTime? CreateDate {get;set;} }
public class HistoryWithdraw { public int Id {get;set;} public int? IdAccount {get;set;} public int? AmountMoney {get;set;} public DateTime? CreateDate {get;set;} public int? Status {get;set;} public DateTime? ConfirmDate {get;set;} public string? BankNumber {get;set;} public string? BankName {get;set;} public string? Fullname {get;set;} public string? Note {get;set;} }
