using System.Security.Cryptography; using System.Text; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using NonBaoHiemVietTin.Data; using NonBaoHiemVietTin.Infrastructure; using NonBaoHiemVietTin.Models;
namespace NonBaoHiemVietTin.Controllers;
public sealed class AccountsController(AppDbContext db):Controller {
 const string AccountKey="account";
 [HttpGet] public IActionResult Login()=>View();
 [HttpPost] public async Task<IActionResult> Login(string usernamelogin,string passwordlogin){var hash=Convert.ToHexString(MD5.HashData(Encoding.UTF8.GetBytes(passwordlogin))).ToLowerInvariant();var a=await db.Accounts.AsNoTracking().FirstOrDefaultAsync(x=>x.Username==usernamelogin&&x.Password==hash&&x.IsSocial==0);if(a==null)return Json(-1);if(a.Status!=true)return Json(0);HttpContext.Session.SetJson(AccountKey,a);return Json(1);}
 [HttpPost] public IActionResult Logout(){HttpContext.Session.Clear();return Json(1);}
 [HttpGet] public async Task<IActionResult> AccountInfo(int page=1){var a=HttpContext.Session.GetJson<Account>(AccountKey);if(a==null)return Redirect("/dang-nhap");return View(await db.Orders.AsNoTracking().Where(x=>x.IdAccount==a.Id).OrderByDescending(x=>x.Id).Skip((page-1)*4).Take(4).ToListAsync());}
 [HttpGet] public async Task<IActionResult> AccountWheel(int page=1){var a=HttpContext.Session.GetJson<Account>(AccountKey);if(a==null)return Redirect("/dang-nhap");return View(await db.Wheels.AsNoTracking().Where(x=>x.IdAccount==a.Id).OrderByDescending(x=>x.Id).Skip((page-1)*10).Take(10).ToListAsync());}
 [HttpGet] public async Task<IActionResult> AccountRecharge(int page=1){var a=HttpContext.Session.GetJson<Account>(AccountKey);if(a==null)return Redirect("/dang-nhap");return View(await db.HistoryRecharges.AsNoTracking().Where(x=>x.IdAccount==a.Id).OrderByDescending(x=>x.Id).Skip((page-1)*10).Take(10).ToListAsync());}
 [HttpGet] public async Task<IActionResult> AccountWithdraw(int page=1){var a=HttpContext.Session.GetJson<Account>(AccountKey);if(a==null)return Redirect("/dang-nhap");return View(await db.HistoryWithdraws.AsNoTracking().Where(x=>x.IdAccount==a.Id).OrderByDescending(x=>x.Id).Skip((page-1)*10).Take(10).ToListAsync());}
 [HttpPost] public async Task<IActionResult> Register(Account model){if(string.IsNullOrWhiteSpace(model.Username)||string.IsNullOrWhiteSpace(model.Email)||string.IsNullOrWhiteSpace(model.Password))return Json(-1);if(await db.Accounts.AnyAsync(x=>x.Username==model.Username&&x.IsSocial==0))return Json(0);if(await db.Accounts.AnyAsync(x=>x.Email==model.Email&&x.IsSocial==0))return Json(2);model.Password=Convert.ToHexString(MD5.HashData(Encoding.UTF8.GetBytes(model.Password))).ToLowerInvariant();model.IsSocial=0;model.Status=true;model.IdRole=1;model.CreateDate=DateTime.UtcNow;model.Coin=0;model.Spin=3;db.Accounts.Add(model);await db.SaveChangesAsync();HttpContext.Session.SetJson(AccountKey,model);return Json(1);}
 [HttpPost] public async Task<IActionResult> ChangePassword(string oldPassword,string newPassword){var a=HttpContext.Session.GetJson<Account>(AccountKey);if(a==null)return Unauthorized();var current=await db.Accounts.FindAsync(a.Id);if(current==null)return Unauthorized();string H(string s)=>Convert.ToHexString(MD5.HashData(Encoding.UTF8.GetBytes(s))).ToLowerInvariant();if(current.Password!=H(oldPassword))return Json(new{status=false,message="Mật khẩu hiện tại không đúng."});current.Password=H(newPassword);await db.SaveChangesAsync();return Json(new{status=true});}
 [HttpPost] public async Task<IActionResult> Update(Account input){var a=HttpContext.Session.GetJson<Account>(AccountKey);if(a==null)return Unauthorized();var current=await db.Accounts.FindAsync(a.Id);if(current==null)return Unauthorized();current.Fullname=input.Fullname;current.Phone=input.Phone;current.Address=input.Address;current.Image=input.Image;await db.SaveChangesAsync();HttpContext.Session.SetJson(AccountKey,current);return Json(new{status=true});}
}
