using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using NonBaoHiemVietTin.Data;
namespace NonBaoHiemVietTin.Controllers;
public sealed class ProductsController(AppDbContext db):Controller {
 const int PageSize=10;
 [HttpGet] public async Task<IActionResult> Index(string alias,int page=1){var q=db.Products.AsNoTracking().Where(x=>x.IsDelete!=true&&x.Status==true); var category=await db.Categories.FirstOrDefaultAsync(x=>x.Alias==alias); var production=await db.Productions.FirstOrDefaultAsync(x=>x.Alias==alias); if(category!=null)q=q.Where(x=>x.IdCategory==category.Id); else if(production!=null)q=q.Where(x=>x.IdProduction==production.Id); else return NotFound(); ViewBag.Alias=category?.Name??production?.Name; return View(await q.OrderByDescending(x=>x.Id).Skip((page-1)*PageSize).Take(PageSize).ToListAsync());}
 [HttpGet] public async Task<IActionResult> GroupProducts(string alias,string alia,int page=1){var c=await db.Categories.FirstOrDefaultAsync(x=>x.Alias==alias);var g=await db.GroupProducts.FirstOrDefaultAsync(x=>x.Alias==alia);if(c==null||g==null)return NotFound();ViewBag.Alias=g.Name;return View("Index",await db.Products.AsNoTracking().Where(x=>x.IdCategory==c.Id&&x.IdGroupProduct==g.Id&&x.IsDelete!=true&&x.Status==true).OrderByDescending(x=>x.Id).Skip((page-1)*PageSize).Take(PageSize).ToListAsync());}
 [HttpGet] public async Task<IActionResult> ProductDetail(string alias){var p=await db.Products.AsNoTracking().FirstOrDefaultAsync(x=>x.Alias==alias&&x.IsDelete!=true);return p==null?NotFound():View(p);}
 [HttpGet] public async Task<IActionResult> Search(string tukhoa,int page=1){tukhoa=(tukhoa??"").Trim();var q=db.Products.AsNoTracking().Where(x=>x.IsDelete!=true&&x.Status==true&&(x.Name!=null&&x.Name.Contains(tukhoa)));ViewBag.Alias="Tìm kiếm: "+tukhoa;return View("Index",await q.OrderByDescending(x=>x.Id).Skip((page-1)*PageSize).Take(PageSize).ToListAsync());}
 [HttpGet] public async Task<IActionResult> ListName(string term)=>Json(new{data=await db.Products.AsNoTracking().Where(x=>x.IsDelete!=true&&x.Status==true&&x.Name!=null&&x.Name.StartsWith(term??"")).Select(x=>new{x.Name,x.Image,x.Alias}).Take(20).ToListAsync(),status=true});
}
